/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_projecttango_examples_java_floorplanreconstruction_TangoJNINative */
#include "tango-plane-fitting/plane_fitting_application.h"
#ifndef _Included_com_projecttango_examples_java_floorplanreconstruction_TangoJNINative
#define _Included_com_projecttango_examples_java_floorplanreconstruction_TangoJNINative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_projecttango_examples_java_floorplanreconstruction_TangoJNINative
 * Method:    edgeDetection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_projecttango_examples_java_floorplanreconstruction_TangoJNINative_edgeDetection
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
